---
include:
  - board: nice_nano
    shield: urchin_left nice_view_adapter
    # snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: urchin_left

  - board: nice_nano
    shield: urchin_right nice_view_adapter
    artifact-name: urchin_right

  - board: xiao_ble
    shield: urchin_dongle dongle_screen
    cmake-args: -DCONFIG_DONGLE_SCREEN_DEFAULT_BRIGHTNESS=50 -DCONFIG_DONGLE_SCREEN_BRIGHTNESS_STEP=2 -DCONFIG_DONGLE_SCREEN_WPM_ACTIVE=n
    artifact-name: urchin_dongle

  - board: nice_nano
    shield: settings_reset
    artifact-name: settings_reset_nice_nano

  # - board: xiao_ble
  #   shield: totem_left
  #   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  #   artifact-name: totem_left

  # - board: xiao_ble
  #   shield: totem_right
  #   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  #   artifact-name: totem_right

  # - board: xiao_ble
  #   shield: totem_dongle dongle_screen
  #   cmake-args: -DCONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=50 -DCONFIG_DONGLE_SCREEN_BRIGHTNESS_STEP=5 -DCONFIG_DONGLE_SCREEN_WPM_ACTIVE=n
  #   artifact-name: totem_dongle

  - board: xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_xiao_ble
