# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter nice_view_battery
    snippet: studio-rpc-usb-uart
    artifact-name: urchin_left
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter nice_view_battery
    artifact-name: urchin_right

  - board: seeeduino_xiao_ble
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    artifact-name: totem_dongle

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_xiao
